# Generated by Django 5.2.15 on 2026-06-23 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('handler', models.CharField(max_length=255)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=128)),
                ('conversation_metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('source', models.CharField(blank=True, max_length=1024)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField(blank=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('document_metadata', models.JSONField(blank=True, default=dict)),
                ('indexed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_documen_status_ae8bb0_idx'), models.Index(fields=['content_type', 'status'], name='api_documen_content_54fccd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=256)),
                ('chunk_metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'ordering': ('document', 'ordinal'),
            },
        ),
        migrations.CreateModel(
            name='LambdaFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('arn', models.CharField(blank=True, max_length=512)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], db_index=True, default='pending', max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['name', '-created_at'], name='api_lambdaf_name_0fd3ee_idx'), models.Index(fields=['status', '-created_at'], name='api_lambdaf_status_815750_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], db_index=True, max_length=16)),
                ('content', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('tool_call_id', models.CharField(blank=True, max_length=128)),
                ('message_metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='api.message')),
            ],
            options={
                'ordering': ('conversation', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='api_convers_user_id_c08f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agent_name', '-updated_at'], name='api_convers_agent_n_189445_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'ordinal'], name='api_documen_documen_a7d9da_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'ordinal'), name='documentchunk_document_ordinal_unique'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='api_message_convers_ece45b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role', 'created_at'], name='api_message_role_4f3e3a_idx'),
        ),
    ]

